# Override OMT's copy default (defaults to clip.exe which doesn't handle unicode, use wayland clipboard; requires wl-clipboard)

# Note #!important doesn't work in sourced files, so we must rely on unsetting OMT setting clipboard
# (tmux_conf_copy_to_os_clipboard)

bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'wl-copy'

bind-key -T root DoubleClick1Pane \
  select-pane -t = \; \
  if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" \
    { send-keys -M } \
    { copy-mode -H ; send-keys -X select-word ; run-shell -d 0.3 ; send-keys -X copy-pipe-and-cancel 'wl-copy' }

bind-key -T root TripleClick1Pane \
  select-pane -t = \; \
  if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" \
  { send-keys -M } \
  { copy-mode -H ; send-keys -X select-line ; run-shell -d 0.3 ; send-keys -X copy-pipe-and-cancel 'wl-copy' }
