# /Users/alex/.config/tmuxinator/config.yml

name: config
root: ~/.config

# Optional tmux socket
# socket_name: foo

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks

# Runs on project start, always
# on_project_start: command

# Run on project start, the first time
# on_project_first_start: command

# Run on project start, after the first time
# on_project_restart: command

# Run on project exit ( detaching from tmux session )
# on_project_exit: command

# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

windows:
  - env:
      layout: ef17,415x86,0,0{307x86,0,0,1,107x86,308,0[107x43,308,0,5,107x42,308,44,6]}
      root: ~
      panes:
        - editor: 
            - vcsh enter env
            - cd ~/.config
            - nvim .
        - shell: 
        - dotfiles-repo:
            - vcsh enter env

  - editor:
      layout: ef17,415x86,0,0{307x86,0,0,1,107x86,308,0[107x43,308,0,5,107x42,308,44,6]}
      root: ~/.config/nvim
      panes:
        - editor:
            - vcsh enter editors
            - nvim .
        - shell: 
        - editors-repo:
            - vcsh enter editors

  - bootstrap:
      layout: ef17,415x86,0,0{307x86,0,0,1,107x86,308,0[107x43,308,0,5,107x42,308,44,6]}
      root: ~/repos/system-bootstrap
      panes:
        - editor: nvim .
        - project-shell: #shell
        - dotfiles-repo:
            - cd ~
            - vcsh enter bootstrap

